# docker-compose.yml (GitHub 프로젝트 루트)
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: safe_walk_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - safe_walk_network

  redis:
    image: redis:7-alpine
    container_name: safe_walk_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - safe_walk_network

  app:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: safe_walk_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      - mysql
      - redis
    networks:
      - safe_walk_network

volumes:
  mysql_data:
  redis_data:

networks:
  safe_walk_network:
    driver: bridge