spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 validate 고려
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false  # 운영에서는 false 권장
        use_sql_comments: false  # 운영에서는 false 권장


  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    servers:
      - url: https://api.safewalk.cloud/api
        description: Production Server
      - url: http://localhost:8080/api
        description: Local Development Server



server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api


# 로깅 설정
logging:
  level:
    root: INFO
    yys.safewalk: INFO


kakao:
  api:
    key: ${KAKAO_API_KEY:your-kakao-api-key}




---
# 테스트 환경 설정
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

server:
  port: 0  # 랜덤 포트 사용

# 테스트용 더미 값
kakao:
  api:
    key: test-kakao-api-key

# 테스트 로깅 설정
logging:
  level:
    root: WARN
    yys.safewalk: DEBUG
    org.springframework.web: DEBUG